### ISSUE TITLE
[Research] "Roadmap" section for the Community-Handbook

### ISSUE THREAD

**Issue by jaskiratsingh2000** [jaskiratsingh2000/Google-Season-of-Docs#18]
Roadmap is important for the CHAOSS project as they are working on many aspects. I would be writing the specific targets and goals of the CHAOSS Community in the Roadmap Section of the gitbook.

- [x] Read some articles for understanding how to define Terminology
- [x] Explored the website
- [x] Discussion with community members

**Comment by jaskiratsingh2000** [comment]
Wrote about the General Roadmap within the gitbook
